learn/learn/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.homepage, name="home"),
    path("about/", views.about, name="about"),
    
    
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
] 
#  this line of code is for images 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learn/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"


urlpatterns = [
    path("", views.posts_list, name="list"),
    path("new-post/", views.new_post, name="new-post"),
    path("<slug:slug>", views.post_page, name="page"),
]

learn/users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

learn/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    auther = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

learn/users/models.py
from django.db import models

# Create your models here.

learn/posts/forms.py
from django import forms
from . import models

class createPost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','slug','banner']

learn/learn/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("Hello World! Im Home.")
    return render(request, "home.html")

def about(request):
    # return HttpResponse("This is my about Page")
    return render(request, "about.html")

learn/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, "posts/posts_list.html", { "posts": posts })

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, "posts/post_page.html", { "post": post })

@login_required(login_url="/users/login")
def new_post(request):
    if request.method == "POST":
        form = forms.createPost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.auther = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.createPost()
    return render(request, "posts/post_new.html", { "form": form })

learn/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {'form' : form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm() 
    return render(request, "users/login.html", {'form' : form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

learn/posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}
    new post
{% endblock %}

{% block content %}
    <section>
        <h1>new post</h1>
        <form action="{% url 'posts:new-post' %}" enctype="multipart/form-data" class="form-with-validation" method="post">
            {% csrf_token %}

            {{ form }}

            <button class="form-submit"> add post  </button>
        </form>
    </section>
{% endblock %}

learn/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}

<section>
    <img class="banner" src="{{ post.banner.url }}" alt="{{ post.title }}">
    <h1> {{ post.title }} </h1>
    <p> {{ post.body }} </p>
    <p> {{ post.date }} </p>

</section>

{% endblock %}

learn/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Post
{% endblock %}

{% block content %}

    <section>
        <h1>Posts</h1>

        {% for post in posts %}
            <article>
                <h2> <a href="{% url 'posts:page' slug=post.slug %}"> {{ post.title }} </a> </h2>
                <p> {{ post.body }} </p>
                <p> {{ post.date }} by {{ post.auther }} </p>
            </article>
        {% endfor %}
    </section>

{% endblock %}

learn/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About Page</h1>
    <h2>Check out my <a href="/">Home</a> page  </h2>
{% endblock %}

learn/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block content %}

    <h1>Home Page</h1>
    <h2>Check out my <a href="/about">about</a> page  </h2>

{% endblock %}

learn/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
</head>
<body>
    <nav>
        <a href="{% url 'home' %}">Home</a> | 
        <a href="{% url 'about' %}">About</a> | 
        <a href="{% url 'posts:list' %}">Post List</a> | 
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}">New Post</a> |
            <form action="{% url 'users:logout' %}" class="logout" method="post">
                {% csrf_token %}
                <button class="logout-button">Logout</button>
            </form>
        {% else %}
            <a href="{% url 'users:register' %}">Register User</a> | 
            <a href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

learn/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    Login User
{% endblock %}

{% block content %}

<h1>Login user</h1>
<form class="form-with-validation" action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <button>Submit</button>
</form>
{% endblock %}

learn/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
Register User
{% endblock %}

{% block content %}

<h1>Register new user</h1>
<form class="form-with-validation" action="{% url 'users:register' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <button>Submit</button>
</form>

{% endblock %}